### ISSUE TITLE
在RecyclerViewAndRecyclerViewActivity中上滑动到底部 然后左滑 下拉失效 

### ISSUE THREAD

**Issue by sher-loki** [hufeiyang/demo01#1]

**Comment by hufeiyang** [comment]
我这边没有复现，不确定是啥问题~

**Comment by hufeiyang** [comment]
你好，已经复现：滑到底，切换到第二个tab、再切到第三个tab，再切回第二个tab，然后上滑是失效的。
原因：使用时，在切换tab时 设置内层fragment有问题，最后切回第二个tab时，同时走了第一个fragment的onStart，所以此时设置的内层RecyclerView就是第一个tab的，所以失效。

解决：判断当前fragment是否是viewPager正在展示的，是 就 把 RecyclerView设置给为内层RecyclerView。

此问题 不是 控件NestedScrollingParent2LayoutImpl3的问题，是使用方式的问题。
